{{- if and .Values.secrets (or .Values.secrets.dbUser .Values.secrets.jwtSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceName }}
    app.kubernetes.io/part-of: banking-platform
type: Opaque
stringData:
  {{- if .Values.secrets.dbUser }}
  POSTGRES_USER: {{ .Values.secrets.dbUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_ISSUER: {{ .Values.secrets.jwtIssuer | quote }}
  {{- end }}
{{- end }}

