apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceName }}
    app.kubernetes.io/part-of: banking-platform
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      {{- if and (eq .Values.serviceType "NodePort") .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
    {{- if .Values.grpcPort }}
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}
    {{- end }}
